# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-03 12:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sklepmuzyczny', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disc',
            name='carts',
        ),
        migrations.DeleteModel(
            name='Disc',
        ),
    ]
