# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-17 08:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sklepmuzyczny', '0002_auto_20160615_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sklepmuzyczny.Cart')),
                ('disc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sklepmuzyczny.Disc')),
            ],
        ),
    ]
