# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-18 07:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sklepmuzyczny', '0003_cartentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=200)),
                ('nazwisko', models.CharField(max_length=200)),
                ('adres', models.CharField(max_length=200)),
                ('ulica', models.CharField(max_length=200)),
                ('telefon', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sklepmuzyczny.Cart')),
            ],
        ),
    ]
