# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-18 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklepmuzyczny', '0005_auto_20160618_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
