# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-18 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklepmuzyczny', '0006_cart_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='disc',
            name='price',
            field=models.FloatField(default=10.5),
        ),
    ]
