# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-18 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklepmuzyczny', '0007_disc_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='sum_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='sum_price',
            field=models.FloatField(default=0),
        ),
    ]
